### ISSUE TITLE
Failed to load Figma file

### ISSUE THREAD

**Issue by Tim-arts** [yannbf/mealdrop#9]
Hello Yann, I've this error while opening the design tab for a component:

![image](https://user-images.githubusercontent.com/10064887/127930179-043468b7-430c-4252-83b3-25ec2cd56fcf.png)

I've tried to create a **.env** file with my *FIGMA_TOKEN* key but still it doesn't work. Where should I set up this token?

**Comment by Tim-arts** [comment]
Okay I've found the solution, sorry for the opened issue. For anyone who will be looking at the answer, I've done it like this:

preview.ts
`
export const parameters = {
    ...
    design: {
        accessToken: process.env.FIGMA_TOKEN
    }
}
`

and in your .env, you declare it this way:
`FIGMA_TOKEN=<token>`

**Comment by yannbf** [comment]
Hey @Tim-arts, the correct and automatic way is to define a [STORYBOOK_FIGMA_ACCESS_TOKEN](https://github.com/pocka/storybook-addon-designs/blob/c3ea46036582a3166c65495eb6c82371a2e15884/packages/examples/stories/docs/figspec/README.stories.mdx#usage) variable in your env or secrets file :)

**Comment by Tim-arts** [comment]
Hello Yann, thank you for your quick response! I'm going to change it this way then :)
